---
title: "R Notebook"
output: html_notebook
---




```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(dplyr)

### Load and summarize data

# read latest covid deaths data from JHU
covid <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-23-2020.csv")

# summarize infection cases by country
covid <- select(covid, Province_State, Country_Region, Deaths)

covid_summary <- covid %>% 
  select(Province_State, Country_Region, Deaths) %>% 
  group_by(Country_Region) %>% 
  summarize(total = sum(Deaths, na.rm = TRUE))

# read world population data from data.worldbank.org
population <- read_csv("population_2018.csv")
population$pop_2018 <- as.numeric(population$pop_2018)

# Join dfs
covid_joined <- covid_summary %>% 
  left_join(population,
            by = "Country_Region")

# calculate deaths per 1 million population 
covid_joined$deaths_per_million <- covid_joined$total/(covid_joined$pop_2018/1000000)

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(knitr)

# create table with selected countries
covid_table <- covid_joined %>% 
  select(Country_Region, deaths_per_million) %>%
  filter(Country_Region %in% c("US", "China", "Italy", "Korea", "Japan", "United Kingdom",
                               "Mexico", "Canada", "India", "Sweden", "Norway", "France", "Spain",
                               "Brazil", "South Korea", "Argentina", "South Africa", "Egypt",
                               "Russia", "Finland", "Denmark"))

covid_table %>% 
  spread(Country_Region, deaths_per_million) %>% 
  kable()

```


```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(ggplot2)

ggplot(covid_table, aes(x = reorder(Country_Region, deaths_per_million),
                        y = deaths_per_million)) +
         geom_bar(stat = "identity", fill = "blue") +
  coord_flip() +
  theme_economist() +
  labs(title = "COVID-19 deaths per 1 million population",
       subtitle = "Selected countries as of June 23, 2020",
       caption = "Source: Johns Hopkins CSSE.",
       x = "",
       y = "") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0.0))


```

